import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Veg Pulao',
    cookTime: '20-30',
    price: 20,
    favorite: false,
    origins: ['India','Telangana'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['Lunch', 'Dinner'],
  },
  {
    id:'2',
    name: 'Pasta',
    price: 10,
    cookTime: '10-15',
    favorite: true,
    origins: ['Italian'],
    stars: 4.7,
    imageUrl: 'assets/food-2.png',
    tags: ['Snack', 'Breakfast','Dinner'],
  },
  {
    id:'3',
    name: 'mazaa',
    price: 2,
    cookTime: '1-2',
    favorite: false,
    origins: ['India'],
    stars: 3.5,
    imageUrl: 'assets/food-3.png',
    tags: ['CoolDrinks', 'Beverages'],
  },
  {
    id:'4',
    name: 'Burger',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood'],
  },
  {
    id:'5',
    name: 'Custard',
    price: 4,
    cookTime: '20-25',
    favorite: false,
    origins: ['India'],
    stars: 3.0,
    imageUrl: 'assets/food-5.png',
    tags: ['Snack'],
  },
  {
    id:'6',
    name: 'Cake',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.png',
    tags: ['Snack', 'Cake'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 6 },
  { name: 'Snack', count: 3 },
  { name: 'Cake', count: 1 },
  { name: 'Lunch', count: 1 },
  { name: 'Breakfast', count: 1 },
  { name: 'FastFood', count: 1 },
  { name: 'Dinner', count: 2 },
  { name: 'CoolDrink', count: 1 },
  { name: 'Beverages', count: 1 },
]
